import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";

const BlogDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query; 

  const [blogData, setBlogData] = useState<any>(null); 

  useEffect(() => {
    if (id) {
     
      fetch(`http://localhost:5001/blogs/${id}`)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Failed to load blog post");
          }
          return response.json();
        })
        .then((data) => {
          setBlogData(data);
        })
        .catch((error) => {
          console.error("Error fetching blog post:", error);
        });
    }
  }, [id]);

  return (
    <>
      <Head>
        <title>Store - {blogData?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={blogData?.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={blogData?.image} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">{blogData?.category}</span>

                    <span>
                      <span className="cl4">By</span> {blogData?.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{blogData?.date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{blogData?.title}</h4>

                  <p className="stext-117 cl6 p-b-26">{blogData?.content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default BlogDetail;
