import type { NextPage } from "next";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";

const Blog: NextPage = () => {
  const [blogs, setBlogs] = useState([]); 
  const [searchQuery, setSearchQuery] = useState(""); 
  const [categoryFilter, setCategoryFilter] = useState(""); 

  useEffect(() => {
   
    const fetchBlogs = async () => {
      let apiUrl = "http://localhost:5001/blogs";

      
      if (categoryFilter) {
        apiUrl += `?category_like=${categoryFilter}`;
      }
      if (searchQuery) {
        apiUrl += `${categoryFilter ? "&" : "?"}q=${searchQuery}`;
      }

      try {
        const response = await fetch(apiUrl);
        if (response.ok) {
          const data = await response.json();
          setBlogs(data);
        } else {
          console.error("Failed to fetch blogs");
        }
      } catch (error) {
        console.error("Error fetching blogs:", error);
      }
    };

    
    fetchBlogs();
  }, [categoryFilter, searchQuery]);

  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {blogs.length > 0 ? (
                  blogs.map((blog) => (
                    <BlogItem key={blog.id} blog={blog} />
                  ))
                ) : (
                  <p>There are no results with your search.</p>
                )}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form className="bor17 of-hidden pos-relative">
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />

                  <button className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => setCategoryFilter("Fashion")}
                      >
                        Fashion
                      </button>
                    </li>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => setCategoryFilter("Beauty")}
                      >
                        Beauty
                      </button>
                    </li>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => setCategoryFilter("streetstyle")}
                      >
                        Street Style
                      </button>
                    </li>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => setCategoryFilter("lifestyle")}
                      >
                        Life Style
                      </button>
                    </li>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => setCategoryFilter("diy")}
                      >
                        DIY & Crafts
                      </button>
                    </li>

                    
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Blog;
