import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../components/PageTitle";
import AboutContent from "../components/AboutContent";

interface AboutPageData {
  title: string;
  first_content: string;
  second_content: string;
  third_content: string;
  first_image: string;
  second_image: string;
  second_title: string;
  fourth_content: string;
  fifth_content: string;
  author: string;
}

const About: NextPage<AboutPageData> = ({
  title,
  first_content,
  second_content,
  third_content,
  first_image,
  second_image,
  second_title,
  fourth_content,
  fifth_content,
  author,
}) => {
  return (
    <>
      <Head>
        <title>Store - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="About Us" />
      <AboutContent
        title={title}
        first_content={first_content}
        second_content={second_content}
        third_content={third_content}
        first_image={first_image}
        second_image={second_image}
        second_title={second_title}
        fourth_content={fourth_content}
        fifth_content={fifth_content}
        author={author}
      />
    </>
  );
};

export default About;


export const getServerSideProps: GetServerSideProps<AboutPageData> = async () => {
  const res = await fetch("http://localhost:5001/about_page");
  const data = await res.json();

  return {
    props: data,
  };
};
